language: objective-c
osx_image: xcode8.1
xcode_project: CIDemo.xcodeproj
xcode_scheme: CIDemo
xcode_sdk: iphonesimulator9.3
script: xcodebuild test -project CIDemo.xcodeproj -scheme CIDemo -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
