language: objective-c
env:
global:
- secure: "lv29RAXlNbgbkZ4PpdQ5BeVf5dAkZNzegFsTFfXjA2a1jxcWD9cSX0KQLXNtA3bBH7awUutVl6aeElHZbDwuj/TYmnUwArerhh/lrhfJ6BevC3p2zLEru20EVY7/XLWWLy5Xz4iyETwWnmeoLBehKkRqygtacgfvgkzdmLZiNoWHa4yFlAam/2EyYIgmlUPemeljAg8JQG6pC0kYVNmJgxppUudRCle5TCF11M/HolzLj3pir93uN0mnf47WPmakyN1Mca82Wp4ka6Hk8qyNtDDwR1eIdE8AoWHhYO8/oczu/Hhem3mf77Kk6V7X4bPcdiqxtUmybXbbppmzNOUMfGMA4jjeR4GpiDC/ZMFXeuVj2urauk7gbwVs9cQ+3di35OF0WVTBK0s4zlU3HfYldmHZnss9jxjGoiWAfNSUSu3Nwok/1IWq59/r5ImnIDWfOT2hUFpIkJkTf1LUuxmwrWnZUeMVaUHk0ou+cDKAIx4whAWXRozXxjFtbrqK49Hf4M59S2Vvbhvvq2S1Tg7+Geduxv3/KmJXCClxJ50s4e6+cSJ7Wo8lb4ySCdH9cMAxR2dfX81wxnJXrFNjkGfTq52K4FnG4NpeGaLMWFv02olGszVTul1TxIt78rJkjLJ37d19JHoE0l09ywYtFYND2GEqOimvSI6T78eqRy7YQGw="
- APP_NAME="CIDemo"
- XCODE_SCHEME="$APP_NAME"
- UNIT_TEST_SCHEME="CIDemoTests"
- 'DEVELOPER_NAME="iPhone Distribution: Vikrant Labde"'
- PROJECT_DIRECTORY="$PWD/"
- SCRIPT_FOLDER="travis-scripts"
- CERT_FOLDER="certfolder"
- INFO_PLIST="$PROJECT_DIRECTORY/$APP_NAME/$APP_NAME/$APP_NAME-Info.plist"
before_install:
- openssl aes-256-cbc -k "$OPENSSL_PASSWORD" -in repo/certfolder/CIDemo_Distribution_Profile.mobileprovision.enc -d -a -out repo/certfolder/CIDemo_Distribution_Profile.mobileprovision
- openssl aes-256-cbc -k "$OPENSSL_PASSWORD" -in repo/certfolder/CIDemoDistribution.cer.enc -d -a -out repo/certfolder/CIDemoDistribution.cer
- openssl aes-256-cbc -k "$OPENSSL_PASSWORD" -in repo/certfolder/CIDemoDistributionKey.p12.enc -d -a -out repo/certfolder/CIDemoDistributionKey.p12
before_script:
- ./travis-scripts/add-key.sh
- ./travis-scripts/update-bundle.sh
osx_image: xcode8.1
script: xcodebuild test -project CIDemo.xcodeproj -scheme CIDemo -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' -configuration Release OBJROOT=${PROJECT_DIRECTORY%/}/build SYMROOT=${PROJECT_DIRECTORY%/}/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./travis-scripts/ipa-signing.sh
after_script:
- ./travis-scripts/delete-key.sh
