language: objective-c
env:
global:
- secure: VoGPweK0K3RxdlH++DJz9bXgOn1mJls7xNARX2z14uAyTZK/CTKckfXL1DYKke0FmKy7iQv5mqoOAkBHDRpFgTXHVQ0VllrdiaZzTfuBwZ0Cfsgl/AmgQeOEUZkiuwt4M2NaQP5c9uHUDPgzettK5f8RLz8i4BNddAz4N6maj75hmRwtMiJtL2dtRv86Owl1UNsBwLZyGUSj5PKp4ZEewCUoTD/D+xWDt8R/XtzzuKpRiNKBNH3ud0CH1VM4QMLk6H1d0QLQ683Q9V1n9ZMiOdxv9KOPNYkfBpHtaCk/8ZpNIPlzOxZK4vqR9p755AYZyGS0gouks0LURajuxlkNAJ1glXjJ7RFrlkX+mMzLVoYexQBFi/3Db92HCpXbBcCeAVMcgRy5Ny0kqIYSSa3Yy4J5qY8ibfS1af7Xmq1VZH74jr+PXQSL88zYnGT0SKtWVTTZ3E+KuiN1Rm+IcRo3pY2YoRLzkj9lvh+Uxaa7YXmJGRkN6B7rE0mFC17qrnoVAKfkxUnLwqIFYQnXjzegiJZZMUiMQca/D4k8TPwfrTuBu9vfLkreWiVx4xF0s2XLCTPSnFo+rrWBjBIigFOrCbLy8rY8Anmvi6hE7jmDf8FiBgcNcsda1RpeRgmWbHW/rfHdo4UumbMv34OqmnIWrLY3kNwixmtwIKXVGd9cu/g=
- APP_NAME="CIDemo"
- XCODE_SCHEME="$APP_NAME"
- UNIT_TEST_SCHEME="CIDemoTests"
- 'DEVELOPER_NAME="iPhone Distribution: Vikrant Labde"'
- PROJECT_DIRECTORY="$PWD/"
- SCRIPT_FOLDER="travis-scripts"
- CERT_FOLDER="certfolder"
- INFO_PLIST="$PROJECT_DIRECTORY/$APP_NAME/$APP_NAME/$APP_NAME-Info.plist"
before_install:
- openssl aes-256-cbc -k "$OPENSSL_PASSWORD" -in ./certfolder/CIDemo_Distribution_Profile.mobileprovision.enc -d -a -out ./certfolder/CIDemo_Distribution_Profile.mobileprovision
- openssl aes-256-cbc -k "$OPENSSL_PASSWORD" -in ./certfolder/CIDemoDistribution.cer.enc -d -a -out ./certfolder/CIDemoDistribution.cer
- openssl aes-256-cbc -k "$OPENSSL_PASSWORD" -in ./certfolder/CIDemoDistributionKey.p12.enc -d -a -out ./certfolder/CIDemoDistributionKey.p12
before_script:
- ./travis-scripts/add-key.sh
- ./travis-scripts/update-bundle.sh
osx_image: xcode8.1
script: xcodebuild test -project CIDemo.xcodeproj -scheme CIDemo -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' -configuration Release OBJROOT=${PROJECT_DIRECTORY%/}/build SYMROOT=${PROJECT_DIRECTORY%/}/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./travis-scripts/ipa-signing.sh
after_script:
- ./travis-scripts/delete-key.sh
